language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -r requirements.txt
# command to run tests
script: nosetests -v usd_nis.py
after_success:
  - coveralls
